"""Game constants for Skull King."""

# Game limits
MAX_PLAYERS = 8
MIN_PLAYERS = 2
MAX_ROUNDS = 10

# Card mechanics
HARRY_THE_GIANT_DISCARD_COUNT = 2
MAX_OPPONENTS_TRACKED = 3
HIGH_CARD_THRESHOLD = 10

# RL Bot thresholds
MERMAID_SKULL_KING_SYNERGY = 0.7
FOURTEENS_BONUS_VALUE = 0.1
HAND_STRENGTH_LOW = 0.3
HAND_STRENGTH_HIGH = 0.6
DIFFICULTY_EASY = 0.3
DIFFICULTY_MEDIUM = 0.6
DIFFICULTY_HARD = 0.8
ESCAPE_RATIO_THRESHOLD = 0.5
SKULL_KING_PIRATE_SYNERGY = 0.3
TIGRESS_VALUE = 0.2
BID_CONFIDENCE_THRESHOLD = 0.5
UNDERBID_PENALTY = 0.15
OVERBID_PENALTY = 0.1
WIN_PROBABILITY_THRESHOLD = 0.6
ESCAPE_PROBABILITY_THRESHOLD = 0.4

# Gym environment
OBSERVATION_SPACE_SIZE = 74
ACTION_SPACE_SIZE = 74
MAX_HAND_SIZE = 10
CARDS_PER_TRICK = 8

# RL Bot observation space dimensions
MAX_PLAYERS_IN_TRICK = 4
OPPONENT_PATTERN_DIMENSIONS = 6
CARD_ENCODING_DIMENSIONS = 9

# RL Bot strength thresholds
HIGH_STRENGTH_THRESHOLD = 0.7
LATE_ROUND_THRESHOLD = 5
MIN_PIRATES_FOR_BONUS = 2
SUIT_CONCENTRATION_FACTOR = 0.6
MIN_SUIT_COUNT = 3

# Publisher service
REDIS_PUBLISH_TIMEOUT = 5

# Scoring
BONUS_POINTS_14 = 10
BONUS_POINTS_CAPTURE = 20
BONUS_MERMAID_CAPTURES_SKULL_KING = 40
CORRECT_BID_MULTIPLIER = 20
ZERO_BID_MULTIPLIER = 10
